name: 'PHP Code Quality'
description: 'Sets up PHP and runs code quality tools'
inputs:
  working-directory:
    description: 'Directory to run composer and quality tools in'
    required: true
  php-version:
    description: 'PHP version to use'
    required: false
    default: '7.4'
  composer-options:
    description: 'Additional composer options'
    required: false
    default: '--no-progress'

runs:
  using: "composite"
  steps:
    - name: Setup PHP with Cached Composer
      uses: ./.github/actions/setup-php-composer
      with:
        php-version: ${{ inputs.php-version }}
        working-directory: ${{ inputs.working-directory }}
        composer-options: ${{ inputs.composer-options }}

    - name: Run PHPStan
      working-directory: ${{ inputs.working-directory }}
      run: composer run-script phpstan
      shell: bash

    - name: Run Psalm
      working-directory: ${{ inputs.working-directory }}
      run: composer run-script php:psalm
      shell: bash

    - name: Run PHP CodeSniffer
      working-directory: ${{ inputs.working-directory }}
      run: composer run-script check-cs
      shell: bash
