name: 'Create Plugin Artifact'
description: 'Builds and uploads a plugin artifact for a PR if a plugin directory is modified.'
inputs:
  slug:
    description: 'Plugin slug (directory name under plugins/)'
    required: true
  composer-options:
    description: 'Additional composer options'
    required: false
    default: '--no-progress'
runs:
  using: "composite"
  steps:
    - name: Setup PHP with Cached Composer
      uses: ./.github/actions/setup-php-composer
      with:
        php-version: ${{ inputs.php }}
        working-directory:  plugins/${{ inputs.slug }}
        composer-options: ${{ inputs.composer-options }}

    - name: Create plugin artifact
      working-directory: plugins/${{ inputs.slug }}
      run: |
        echo "${GITHUB_SHA}" > build-sha.txt
        rm -rf plugin-build/${{ inputs.slug }}*
        composer archive -vvv --format=zip --file="plugin-build/${{ inputs.slug }}" --dir="."
        # Extract the zip so artifact upload creates proper structure
        # (avoids double-zip issue where downloaded artifact contains a zip)
        unzip plugin-build/${{ inputs.slug }}.zip -d plugin-build/${{ inputs.slug }}
        rm plugin-build/${{ inputs.slug }}.zip
      shell: bash

    - name: Upload plugin artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.slug }}
        path: plugins/${{ inputs.slug }}/plugin-build/${{ inputs.slug }}
