import "water.css/out/light.min.css";
import "@/styles/globals.css";


// Base styles from WordPress (foundational block styling)
// import '@wordpress/base-styles';

// The fetched global styles from WP (generated by your fetch script)
// import "/hwp-global-styles.css";

export default function App({ Component, pageProps }) {
  return <Component {...pageProps} />;
}
