name: "✨ Feature Request"
description: Suggest a new feature or improvement
title: "[Feature Request]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ## Thank You for taking the time to suggest a feature!
        Your ideas help make our project better for everyone.
        
        Before submitting, we kindly encourage you to browse our [existing feature requests](https://github.com/wpengine/hwptoolkit/issues) 
        to see if your idea has already been suggested. This helps us keep our issues organized and ensures your valuable feedback receives proper attention. 
        Thank you for your understanding!

        <details>
          <summary>Example of a Great User Story</summary>
        
          ### Example: Image Optimization Component for WordPress Headless Toolkit
        
          #### User Story
          As a frontend developer building media-rich headless WordPress sites,
          I want a dedicated image optimization component with responsive handling,
          so that I can deliver faster page loads without implementing complex optimization logic myself.
        
          #### Acceptance Criteria
          - [ ] Create a drop-in Image component that works with WordPress media URLs
          - [ ] Implement automatic responsive sizing based on viewport
          - [ ] Support modern image formats (WebP) with appropriate fallbacks
          - [ ] Integrate lazy loading with zero configuration required
          - [ ] Include simple documentation with before/after performance examples
        
          #### Notes
          The current workflow requires manually handling image optimization, which leads to inconsistent implementations across projects. A standardized component would improve site performance metrics and developer experience while ensuring best practices are followed across all projects using the toolkit.
        
        </details>

  - type: textarea
    id: user-story
    attributes:
      label: User Story
      description: "Describe your feature in terms of who benefits, what it does, and why it matters"
      placeholder: |
        As a [type of user],
        I want [what feature/capability],
        so that [benefit/value].
      value: |
        As a 
        I want 
        so that
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: "Acceptance Criteria"
      description: "What would make this feature complete and ready to ship?"
      placeholder: |
        - [ ] The feature should allow...
        - [ ] The user should be able to...
        - [ ] This should integrate with...

  - type: textarea
    id: notes
    attributes:
      label: "Notes"
      description: "Provide more details about your feature request"
      placeholder: "Explain the feature in more detail - how would it work? What problem does it solve?"
    validations:
      required: true

  - type: dropdown
    id: importance
    attributes:
      label: "How important is this feature to you?"
      description: "This helps us prioritize the request"
      options:
        - Nice to have
        - Important
        - Critical
    validations:
      required: true

  - type: dropdown
    id: contribution
    attributes:
      label: "Would you like to contribute to this feature?"
      description: "We welcome community contributions!"
      options:
        - No, just suggesting
        - I might help with testing
        - Yes, I'd like to implement this
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: "Before submitting"
      description: "Please verify that you've completed the following:"
      options:
        - label: I've searched existing issues to make sure this feature hasn't already been requested
          required: true

  - type: markdown
    attributes:
      value: |
        ## What happens next?
        Our team will review your feature request and may ask clarifying questions.
        We prioritize features based on community interest and alignment with our roadmap.
