name: 'Create Plugin Release'
description: 'Upload zip file to releases tab'
branding:
  icon: 'upload-cloud'
  color: 'blue'

inputs:
  github_token:
    description: 'GitHub Token'
    required: true
  php:
    description: 'PHP version to use'
    required: true
  directory:
    description: 'Plugin slug (directory name under plugins/)'
    required: true
  composer-options:
    description: 'Additional composer options'
    required: false
    default: '--no-progress'

outputs:
  zip-path:
    description: 'Path to zip file'
    value: ${{ steps.zip-main-release-for-github.outputs.zip-path }}

runs:
  using: 'composite'
  steps:
    - id: prepare
      name: Prepare Environment
      run: sudo apt-get update && sudo apt-get install zip rsync -y
      shell: bash

    - name: Setup PHP with Cached Composer
      uses: ./.github/actions/setup-php-composer
      with:
        php-version: ${{ inputs.php }}
        working-directory:  plugins/${{ inputs.slug }}
        composer-options: ${{ inputs.composer-options }}

    - id: create-asset-release-version
      name: Create asset release version without quotes
      run: |
        ASSET_RELEASE_VERSION=$(echo ${{ env.VERSION }} | tr -d '"')
        echo "ASSET_RELEASE_VERSION=$ASSET_RELEASE_VERSION" >> $GITHUB_ENV
      shell: bash

    - name: Create plugin artifact
      working-directory: plugins/${{ inputs.slug }}
      run: |
        mkdir -p plugin-build
        rm -f plugin-build/${{ inputs.slug }}-*.zip
        composer archive -vvv --format=zip --file="plugin-build/${{ inputs.slug }}.${{ env.VERSION }}" --dir="."
      shell: bash

    - id: upload-main-release-to-github
      name: Uploads the main release zip file to GitHub
      uses: softprops/action-gh-release@v2
      with:
        token: ${{ inputs.github_token }}
        files: plugins/${{ inputs.slug }}/plugin-build/${{ inputs.slug }}.${{ env.VERSION }}.zip
        asset_name: ${{ inputs.slug }}.${{ env.VERSION }}.zip
        tag_name: "${{ env.NAME }}@${{ env.ASSET_RELEASE_VERSION }}"
        overwrite: true
