import { Lato, Open_Sans } from "next/font/google";
import "./globals.css";

// Note: You can use nested layouts too in Next.js - https://nextjs.org/docs/pages/building-your-application/routing/pages-and-layouts#per-page-layouts
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";

const lato = Lato({
  variable: "--font-lato",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata = {
  title: "Sample Headless WordPress Site",
  description: "Generated by hwptoolkit",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${lato.variable} ${openSans.variable} antialiased`}>
        <main className="bg-stone-100 text-gray-800 min-h-screen">
          <Header />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
