import '@wordpress/base-styles';         // WordPress foundational styles.
import '@/styles/hwp-global-styles.css'; // The fetched global styles from WP (generated by your fetch script).
import "@/styles/globals.css";           // Optional custom global styles.

export default function App({ Component, pageProps }) {
  return <Component {...pageProps} />;
}
