#!/usr/bin/env node

/**
 * Generate .env file with calculated ports for this example
 */

const { getPorts } = require('../../../../scripts/get-ports.js');
const fs = require('fs');
const path = require('path');

const examplePath = 'vanilla/toolbar-demo';
const ports = getPorts(examplePath);

// Create .env file for Vite
const envContent = `# Auto-generated by setup-env.js - DO NOT EDIT MANUALLY
VITE_FRONTEND_PORT=${ports.FRONTEND_PORT}
VITE_WP_URL=http://localhost:${ports.WP_PORT}
VITE_WP_PORT=${ports.WP_PORT}
VITE_WP_TEST_PORT=${ports.WP_TEST_PORT}
`;

const envPath = path.join(__dirname, '../example-app/.env');
fs.writeFileSync(envPath, envContent);

console.log(`✓ Generated .env for ${examplePath}`);
console.log(`  Frontend: ${ports.FRONTEND_PORT}`);
console.log(`  WordPress: ${ports.WP_PORT}`);
console.log(`  WP Test: ${ports.WP_TEST_PORT}`);

// Update .wp-env.json
const wpEnvConfig = {
  phpVersion: '8.0',
  plugins: [
    'https://github.com/wp-graphql/wp-graphql/releases/latest/download/wp-graphql.zip'
  ],
  config: {
    WP_DEBUG: true,
    WP_DEBUG_LOG: true,
    GRAPHQL_DEBUG: true
  },
  port: ports.WP_PORT,
  testsPort: ports.WP_TEST_PORT,
  mappings: {
    db: './wp-env/db',
    'wp-content/mu-plugins': './mu-plugin.php',
    '.htaccess': './.htaccess'
  },
  lifecycleScripts: {
    afterStart: 'wp-env run cli -- wp rewrite structure \'/%postname%/\' --hard && wp-env run cli -- wp theme activate twentytwentyfour'
  }
};

const wpEnvPath = path.join(__dirname, '../.wp-env.json');
fs.writeFileSync(wpEnvPath, JSON.stringify(wpEnvConfig, null, 2) + '\n');

console.log(`✓ Updated .wp-env.json`);

// Generate mu-plugin.php from template
const muPluginTemplatePath = path.join(__dirname, '../../../../scripts/templates/mu-plugin.php');
const muPluginTemplate = fs.readFileSync(muPluginTemplatePath, 'utf8');
const muPluginContent = muPluginTemplate.replace(/{{FRONTEND_PORT}}/g, ports.FRONTEND_PORT);

const muPluginPath = path.join(__dirname, '../mu-plugin.php');
fs.writeFileSync(muPluginPath, muPluginContent);
console.log(`✓ Generated mu-plugin.php`);

// Copy .htaccess from template
const htaccessTemplatePath = path.join(__dirname, '../../../../scripts/templates/.htaccess');
const htaccessPath = path.join(__dirname, '../.htaccess');
fs.copyFileSync(htaccessTemplatePath, htaccessPath);
console.log(`✓ Generated .htaccess`);
