name: 'Run Codeception Tests'
description: 'Sets up environment and runs Codeception test suites'
inputs:
  working-directory:
    description: 'Plugin directory to run tests in'
    required: true
  php:
    description: 'PHP version'
    required: true
  wordpress:
    description: 'WordPress version'
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php }}
        tools: composer:v2
        coverage: none

    - name: Install dependencies
      uses: ramsey/composer-install@v2
      with:
        working-directory: ${{ inputs.working-directory }}
        composer-options: "--no-progress"