name: Playwright End-to-End Tests

on:
  push:
    branches:
      - main
    paths:
      - "plugins/hwp-previews/**"
  pull_request:
    branches:
      - main
    paths:
      - "plugins/hwp-previews/**"

jobs:
  playwright-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: plugins/hwp-previews

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Install playwright browsers
        run: npx playwright install chromium --with-deps

      - name: Start wp-env
        run: |
          npm run wp-env -- start

      - name: Run Playwright tests
        run: npm run test:e2e

      - name: Stop wp-env
        run: npm wp-env -- stop
