name: Plugin Artifact for PR

on:
  pull_request:
    paths:
      - 'plugins/hwp-previews/**'
      - 'plugins/hwp-previews-plugin/**'

jobs:
  create-plugin-artifact:
    name: Create Plugin Artifact
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create plugin artifact
        uses: ./.github/actions/create-plugin-artifact
        with:
          slug: hwp-previews

      - name: Comment with artifact link
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            const runId = context.runId;
            const artifactUrl = `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${runId}`;
            const body = `ℹ️ [Download the plugin artifact from this workflow run](${artifactUrl}) (see the 'Artifacts' section at the bottom).`;
            await github.rest.issues.createComment({
              issue_number: pr.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body
            });
